version: '3.7'
services:
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
           - "/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2_8
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/dags:/usr/local/airflow/dags"
            - "${PWD}/plugins:/usr/local/airflow/plugins"
            - "${PWD}/requirements:/usr/local/airflow/requirements"
            - "${PWD}/startup_script:/usr/local/airflow/startup"
            # Set this variable to somewhere not under source control to prevent sharing creds
            # Add a connections.json file to it along with any private keys needed for connecting
            # Directory will be mounted and connections in connections.json will be created
            # Connections will not show up in the UI , but are usable in DAGS
            - "${AIRFLOW_LOCAL_CONNECTIONS_DIR}:/usr/local/airflow/files"
        ports:
            - "8080:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
            - ./config/.env.localrunner
